set(CALIPER caliper)
set(CALIPER_URL ${PROJECT_SOURCE_DIR}/files)
set(CALIPER_GZ  Caliper-1.6.0.tar.gz)
set(CALIPER_MD5 "1b2d2a02d35856494e9c7d218f78f0ac")

message(STATUS "Building ${CALIPER}")
ExternalProject_Add(${CALIPER}
 URL ${CALIPER_URL}/${CALIPER_GZ}
 URL_MD5 ${CALIPER_MD5}
 CONFIGURE_COMMAND ${CMAKE_COMMAND}
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
   -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
   -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
   -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
   -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
   -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
   -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
   <SOURCE_DIR>
)
