set(CINCH_UTILS_NAME cinch-utils)

if ( USE_INSTALL_TARGET )
  set( _install_dir ${CINCH_UTILS_NAME}/install )
else()
  set( _install_dir ${CMAKE_INSTALL_PREFIX} )
endif()

message(STATUS "Building ${CINCH_UTILS_NAME}")
ExternalProject_Add(${CINCH_UTILS_NAME}
 DEPENDS ${GASNET_NAME}
 SOURCE_DIR ${PROJECT_SOURCE_DIR}/cinch-utils
 PREFIX ${CINCH_UTILS_NAME}
 INSTALL_DIR ${_install_dir}
 CONFIGURE_COMMAND ${CMAKE_COMMAND}
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
   -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
   -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
   -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
   -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
   -ENABLE_DOCUMENTATION=ON
   <SOURCE_DIR>
   LOG_BUILD 1
)
ExternalProject_get_property(${CINCH_UTILS_NAME} INSTALL_DIR)

if ( USE_INSTALL_TARGET )
  install(DIRECTORY ${INSTALL_DIR}/ DESTINATION ${CMAKE_INSTALL_PREFIX}
    USE_SOURCE_PERMISSIONS)
endif()
