set(HDF5_NAME hdf5)
set(HDF5_URL ${PROJECT_SOURCE_DIR}/files)
set(HDF5_GZ hdf5-1.8.15-patch1.tar.gz)
set(HDF5_MD5 "4467c25ed9c0b126b194a4d9d66c29ac")

ExternalProject_Add(${HDF5_NAME}
  DEPENDS ${SZIP_PACKAGE_NAME} ${ZLIB_PACKAGE_NAME}
  URL ${HDF5_URL}/${HDF5_GZ}
  URL_MD5 ${HDF5_MD5}
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBUILD_STATIC_EXECS:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DHDF5_BUILD_HL_LIB:BOOL=ON
    -DHDF5_BUILD_CPP_LIB:BOOL=OFF
    -DHDF5_BUILD_FORTRAN:BOOL=OFF
    -DHDF5_BUILD_TOOLS:BOOL=OFF
    -DHDF5_PACKAGE_EXTLIBS:BOOL=ON
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
    -DZLIB_PACKAGE_NAME:STRING=${ZLIB_PACKAGE_NAME}
    -DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}
    -DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARY}
    -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
    -DHDF5_ENABLE_SZIP_ENCODING:BOOL=ON
    -DSZIP_PACKAGE_NAME:STRING=${SZIP_PACKAGE_NAME}
    -DSZIP_INCLUDE_DIR:PATH=${SZIP_INCLUDE_DIR}
    -DSZIP_LIBRARY:FILEPATH=${SZIP_LIBRARY}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
)

set(HDF5_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
set(HDF5_LIBRARY     ${CMAKE_INSTALL_PREFIX}/lib/libhdf5.a)
set(HDF5_HL_LIBRARY  ${CMAKE_INSTALL_PREFIX}/lib/libhdf5_hl.a)
