set(LAPACK_NAME lapack)
string(TOLOWER ${LAPACK_NAME} LAPACK_PACKAGE_NAME)
set(LAPACK_URL ${PROJECT_SOURCE_DIR}/files)
set(LAPACK_TAR lapack-3.6.0.tar)
set(LAPACK_MD5 "bab11fba46e31e780f8ea0ffa0815928")

ExternalProject_Add(${LAPACK_NAME}
  URL ${LAPACK_URL}/${LAPACK_TAR}
  URL_MD5 ${LAPACK_MD5}
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DBUILD_COMPLEX=OFF
    -DBUILD_COMPLEX16=OFF
    -DCBLAS=ON
    -DLAPACKE=ON
)

set(LAPACK_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
set(LAPACK_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/liblapacke.a)
