set(LEGION_NAME legion)

if(GASNET_CODNUIT STREQUAL "udp")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DGASNET_CONDUIT_UDP")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${CMAKE_INSTALL_PREFIX}/include/udp-conduit")
   set (CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_INSTALL_PREFIX}/lib/libgasnet-udp-par.a ${CMAKE_INSTALL_PREFIX}/lib/libamudp.a")

 elseif (GASNET_CODNUIT STREQUAL "ibv")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DGASNET_CONDUIT_IBV")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${CMAKE_INSTALL_PREFIX}/include/ibv-conduit")
   set (CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_INSTALL_PREFIX}/lib/libgasnet-ibv-par.a ${CMAKE_INSTALL_PREFIX}/lib/libibverbs.a")
 elseif (GASNET_CODNUIT STREQUAL "mpi")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DGASNET_CONDUIT_MPI -DUSE_GASNET -DGASNETI_BUG1389_WORKAROUND -DDEBUG_REALM -DDEBUG_LEGION -ggdb -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG")
   		       
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${CMAKE_INSTALL_PREFIX}/include -I${CMAKE_INSTALL_PREFIX}/include/mpi-conduit")
   set (CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_INSTALL_PREFIX}/lib/libgasnet-mpi-par.a -lammpi -lmpi")

 else()
   message (ERROR "wrong Gasnet conduit specified")
 endif ()


ExternalProject_Add(${LEGION_NAME}
 DEPENDS ${GASNET_NAME}
 SOURCE_DIR ${PROJECT_SOURCE_DIR}/legion
 CONFIGURE_COMMAND ${CMAKE_COMMAND}
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
   -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
   -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
   -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
   -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
   -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
   -DGASNET_CONDUIT:STRING=${GASNET_CODNUIT}
   <SOURCE_DIR>
)
