set(METIS_NAME metis)
set(METIS_URL ${PROJECT_SOURCE_DIR}/files)
set(METIS_GZ  metis-5.1.0.tar.gz)
set(METIS_MD5 "5465e67079419a69e0116de24fce58fe")

set(PATCH_COMMAND)
if(METIS_INT64)
   set(PATCH_COMMAND patch -p1 < ${PROJECT_SOURCE_DIR}/patches/metis-5.1.0-datatype.patch)
endif(METIS_INT64)

message(STATUS "Building ${METIS_NAME}")
ExternalProject_Add(${METIS_NAME}
 URL ${METIS_URL}/${METIS_GZ}
 URL_MD5 ${METIS_MD5}
 PREFIX third-party
 INSTALL_DIR third-party/install
 UPDATE_COMMAND ""
 PATCH_COMMAND ${PATCH_COMMAND}
 CMAKE_ARGS
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
   -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
   -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
   -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
   -DSHARED:BOOL=${BUILD_SHARED_LIBS}
   -DGKLIB_PATH=<SOURCE_DIR>/GKlib/
   -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
   LOG_BUILD 1
)
ExternalProject_get_property(${METIS_NAME} INSTALL_DIR)
install(DIRECTORY ${INSTALL_DIR}/ DESTINATION ${CMAKE_INSTALL_PREFIX} USE_SOURCE_PERMISSIONS)
