set(METIS_NAME metis)
set(METIS_URL ${PROJECT_SOURCE_DIR}/files)
set(METIS_GZ  metis-5.1.0.tar.gz)
set(METIS_MD5 "5465e67079419a69e0116de24fce58fe")

ExternalProject_Add(${METIS_NAME}
 URL ${METIS_URL}/${METIS_GZ}
 URL_MD5 ${METIS_MD5}
 UPDATE_COMMAND ""
 CMAKE_ARGS
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
   -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
   -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
   -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
   -DGKLIB_PATH=<SOURCE_DIR>/GKlib/
   -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
)
