set(NETCDF_NAME netcdf)
set(NETCDF_URL ${PROJECT_SOURCE_DIR}/files)
set(NETCDF_GZ  netcdf-4.3.3.1.tar.gz )
set(NETCDF_MD5 "5c9dad3705a3408d27f696e5b31fb88c" )

ExternalProject_Add(${NETCDF_NAME}
  DEPENDS
  URL ${NETCDF_URL}/${NETCDF_GZ}
  URL_MD5 ${NETCDF_MD5}
  UPDATE_COMMAND ""
  PATCH_COMMAND patch -p0 < ${PROJECT_SOURCE_DIR}/patches/netcdf.patch
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS} ${SZIP_LIBRARY}
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DENABLE_TESTS=OFF
    -DENABLE_DAP=OFF 
    -DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARY}
    -DSZIP_LIBRARY:FILEPATH=${SZIP_LIBRARY}
    -DHDF5_LIB:FILEPATH=${HDF5_LIBRARY}
    -DHDF5_HL_LIB:FILEPATH=${HDF5_HL_LIBRARY}
    -DHDF5_INCLUDE_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include
    -DCMAKE_INSTALL_LIBDIR:PATH=lib
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
  DEPENDS ${HDF5_NAME}
)

set(NETCDF_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
set(NETCDF_LIBRARY     ${CMAKE_INSTALL_PREFIX}/lib/libnetcdf.a)
