set(THRUST_NAME thrust)
set(THRUST_URL ${PROJECT_SOURCE_DIR}/files)
set(THRUST_GZ  thrust-1.8.2.zip)
set(THRUST_MD5 "06d9325c9ff7201e80dfabc8114bb571")

message(STATUS "Building ${THRUST_NAME}")
ExternalProject_Add(${THRUST_NAME}
 URL ${THRUST_URL}/${THRUST_GZ}
 URL_MD5 ${THRUST_MD5}
 CONFIGURE_COMMAND ""
 BUILD_COMMAND ""
 INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR> ${CMAKE_INSTALL_PREFIX}/include/thrust
)
