set(ZLIB_NAME zlib)
string(TOLOWER ${ZLIB_NAME} ZLIB_PACKAGE_NAME)
set(ZLIB_URL ${PROJECT_SOURCE_DIR}/files)
set(ZLIB_TGZ ZLib.tar.gz)
set(ZLIB_MD5 "10c092840e53a2bfb64fca0a4634ea0b")

message(STATUS "Building ${ZLIB_NAME}")
ExternalProject_Add(${ZLIB_NAME}
  URL ${ZLIB_URL}/${ZLIB_TGZ}
  URL_MD5 ${ZLIB_MD5}
  PREFIX third-party
  INSTALL_DIR third-party/install
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  BUILD_IN_SOURCE 1
  LOG_BUILD 1
)
ExternalProject_get_property(${ZLIB_NAME} INSTALL_DIR)
ExternalProject_Get_Property(${ZLIB_NAME} source_dir)

set(ZLIB_INCLUDE_DIR ${source_dir})
if (CMAKE_BUILD_TYPE MATCHES Debug)
  set(ZLIB_LIBRARIES ${INSTALL_DIR}/lib/${CMAKE_LIBRARY_PREFIX}z_debug${CMAKE_LIBRARY_SUFFIX})
else()
  set(ZLIB_LIBRARIES ${INSTALL_DIR}/lib/${CMAKE_LIBRARY_PREFIX}z${CMAKE_LIBRARY_SUFFIX})
endif()

install(DIRECTORY ${INSTALL_DIR}/ DESTINATION ${CMAKE_INSTALL_PREFIX} USE_SOURCE_PERMISSIONS)
