set(ZLIB_NAME zlib)
string(TOLOWER ${ZLIB_NAME} ZLIB_PACKAGE_NAME)
set(ZLIB_URL ${PROJECT_SOURCE_DIR}/files)
set(ZLIB_TGZ ZLib.tar.gz)
set(ZLIB_MD5 "10c092840e53a2bfb64fca0a4634ea0b")

ExternalProject_Add(${ZLIB_NAME}
  URL ${ZLIB_URL}/${ZLIB_TGZ}
  URL_MD5 ${ZLIB_MD5}
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  LOG_BUILD 1
)

set(ZLIB_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
set(ZLIB_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_LIBRARY_PREFIX}z${CMAKE_LIBRARY_SUFFIX})
